version: "3.9"

networks:
  mayaprotect:
    driver: bridge

services:
  mongo:
    image: mongo:4.2.3
    container_name: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    networks:
      - mayaprotect

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "9002:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - mayaprotect
    depends_on:
      - mongo

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9003:9090"
    volumes:
      - ./data/prometheus:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mayaprotect
    depends_on:
      - metricsfaker
      
  metricsfaker:
    image: pfontaine/metricsfaker:latest
    container_name: metricsfaker
    restart: always
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    ports:
      - "9001:8000"
    networks:
      - mayaprotect
    depends_on:
      - mongo

