version: "3.9"

networks:
  mayaprotect:
    driver: bridge

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - mayaprotect

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "8030:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - mayaprotect
    depends_on:
      - mongo

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mayaprotect
    depends_on:
      - metricsfaker

  metricsfaker:
    image: pfontaine/metricsfaker:latest
    container_name: metricsfaker
    restart: always
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MIN_OWNER=5
      - MAX_OWNER=10
      - MIN_STATIONS_PER_OWNER=5
      - MAX_STATIONS_PER_OWNER=10
      - MIN_HIVES_PER_STATION=4
      - MAX_HIVES_PER_STATION=20
    networks:
      - mayaprotect
    depends_on:
      - mongo

  gethives:
    image: pfontaine/gethiveslist:latest
    container_name: gethives
    restart: always
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=mayaprotect
    networks:
      - mayaprotect
    depends_on:
      - mongo
  
  gethive:
    image: clairedupuich9/getahive:latest
    container_name: gethive
    restart: always
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=mayaprotect
    networks:
      - mayaprotect
    depends_on:
      - mongo
  
  registerstation:
    image: pfontaine/registerstation:latest
    container_name: registerstation
    restart: always
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=mayaprotect
    networks:
      - mayaprotect
    depends_on:
      - mongo

  # posthiveevent:
  #   image: dockerman590/posthiveevent:latest
  #   container_name: posthiveevent
  #   restart: always
  #   environment:
  #     - MONGO_HOST=mongo
  #     - MONGO_PORT=27017
  #     - MONGO_DB=mayaprotect
  #   networks:
  #     - mayaprotect
  #   depends_on:
  #     - mongo

  apigateway:
    image: nginx:latest
    container_name: apigateway
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginxlogs:/var/log/nginx
    networks:
      - mayaprotect
    depends_on:
      - gethives
      - gethive
      # - posthiveevent

  docapi:
    image: swaggerapi/swagger-ui:latest
    container_name: docapi
    restart: always
    ports:
      - "3001:8080"
    volumes:
      - ./openapi.json:/usr/share/nginx/html/openapi.json
    environment:
      - SWAGGER_JSON_URL=/openapi.json
    networks:
      - mayaprotect
